/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 judge.gltf --transform
Author: Sviatoslav Semenov (https://sketchfab.com/svyasem)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/judges-gavel-8d95b6f773474828ac1ee80de45b2e3d
Title: Judge's Gavel
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/judge-transformed.glb');
  return (
    <group {...props} dispose={null}>
      <group
        position={[0, -0.08, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={4.68}
      >
        <group rotation={[-Math.PI, 0, 0]}>
          <group
            position={[-0.05, 0, 0.07]}
            rotation={[0.24, Math.PI / 2, 0]}
            scale={0.01}
          >
            <mesh
              geometry={nodes['JudgeHammer_low_03_-_Default_0'].geometry}
              material={materials['03_-_Default']}
              position={[0.02, 0.04, -7.41]}
            />
          </group>
          <group scale={0.01}>
            <mesh
              geometry={nodes['Wood_02_-_Default_0'].geometry}
              material={materials['02_-_Default']}
              position={[-0.1, 0, 0]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/judge-transformed.glb');
